### ISSUE TITLE
HOL - Setup

### ISSUE THREAD

**Issue by bryan-c-smith** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#11]
There are just too many resources being deployed across too many resource groups.  Having completed the setup steps, I have a SQL VM, two SQL DBs, a SQL DW, Azure AS, and an Azure Data Factory with its own VM/Runtime.  These are spread across 5 resource groups making clean up difficult.  This needs to be simplified.

**Comment by bryan-c-smith** [comment]
In addition, consider scripting all this deployment through a template.  The setup of all these resources takes > 1 hr.

**Comment by paulopsgility** [comment]
We need to pick this up on the next refresh. I am leaving this open for visibility.

**Comment by paulopsgility** [comment]
There was another issue basically with the same comments. I did drop one of the RGs and renamed a couple of them to be easier to locate. 

Note that best practices around use of resource groups would dictate that we have more resource groups not fewer and putting everything into a single resource group, while making it easier to cleanup the lab, gets people that are probably new to Azure used to doing things the wrong way.

**Comment by bryan-c-smith** [comment]
I have to disagree with the notion of a “best practice”. RGs are used to contain resources into a manageable unit. You are thinking of the solution as a production deployment but our customers will be looking at this as a singular lab that they will need to thoroughly remove upon completion. I would go with fewer RGs and use a resource naming convention to subdivide resources within them. At the end of the lab, it’s be ideal if our customers could delete a single RG and know that all resources are removed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paulopsgility** [comment]
Condensed the number of resource groups to 2 (on-prem environment and cloud environment). Also created an ARM template to handle deploying resources that are necessary for the lab but not really the focus of what we are trying to learn. Should make it much easier to deploy and cleanup.
