### ISSUE TITLE
HOL - Ex 2, Step 3

### ISSUE THREAD

**Issue by bryan-c-smith** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#13]
Question marks after table name cause syntax error from SQL Server

USE CohoDW
GO
SELECT t.[name] as [Table], 
       c.[name] as [Column], 
       c.[system_type_id], 
       c.[user_type_id], 
       y.[is_user_defined], 
       y.[name]
FROM **sys.tables??** t JOIN sys.columns c ON t.[object_id] = c.[object_id]
                   JOIN sys.types y ON c.[user_type_id] = y.[user_type_id]
WHERE y.[name] IN ('geography', 'geometry', 'hierarchyid', 'image', 'ntext',
'numeric', 'sql_variant', 'sysname', 'text', 'timestamp', 'uniqueidentifier', 'xml')
  OR (y.[name] IN ('varchar', 'varbinary') AND ((c.[max_length] = -1) or 
                                              (c.max_length > 8000)))
  OR (y.[name] IN ('nvarchar') AND ((c.[max_length] = -1) or 
                               (c.max_length > 4000))) OR y.[is_user_defined] = 1;

**Comment by paulopsgility** [comment]
Removed question marks. I believe was just leftover artifact from the Word to Markdown conversion process.
