### ISSUE TITLE
HOL - step-by-step

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#30]
Several images missing alt-text.

Usually, when I hover over an image in GitHub, I see the alt-text title.  Then, when it's in HTML we see the full alt-text.  On your workshop, I don't see the title either....can you please look into why?  Thanks!

**Comment by paulopsgility** [comment]
Updated some of the old alt-text, added alt-text where it was missing, added all the image text
