### ISSUE TITLE
December Update

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#38]
- Updated screenshots
- Simplified Deployment (template)
- Simplified resource groups

**Comment by DawnmarieDesJardins** [comment]
@Microsoft/migrate-edw-to-azure-sql-data-warehouse-sme-team 
Adding the SME group for review and discussion.

**Comment by DawnmarieDesJardins** [comment]
@mwasham 
Michael,
Please have your team move forward with this update.  Contact me when draft PR is ready for SME review.  Also review open issue #11 in this update.
Thanks,
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing with January 2019 update merge.
