### ISSUE TITLE
HOL Ex1 Task 2

### ISSUE THREAD

**Issue by bryan-c-smith** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#4]
Task 2 asks to specify region for ADF v2.  These regions do not cover all the regions associated with the ADF RunTime.  Users may be confused.  We should add a note to indicate that the RunTime does not need to be in the same region as the ADF.

**Comment by paulopsgility** [comment]
These are the regions that are supported by the SSIS IR. I do expect these to change over time but as of right now that is all I see in the portal. I added some notes when creating data factory and when creating the ssis IR to better explain why we are using the regions we are using.
