### ISSUE TITLE
Where do I get bcp_commands.txt file in Ex 3 Task 1

### ISSUE THREAD

**Issue by falloutxAY** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#41]
Where do I get _bcp_commands.txt_ file in Exercise 3 Task 1? It is **not** in the _labfiles_ folder.

**Comment by DawnmarieDesJardins** [comment]
Hello,
Did you check in the Before the hands on lab document?  It deploys a source environment.  Let me know if that gets you what you need.

**Comment by DawnmarieDesJardins** [comment]
@falloutxAY 
Hello!  Did the Before the hands on lab document give you what you need to complete the workshop?
Thanks, Dawnmarie

**Comment by falloutxAY** [comment]
Thanks. I misunderstood the lab instructions. Did not realise it was on the before the HOL lab machine. Thank you

**Comment by falloutxAY** [comment]
Resolved
