### ISSUE TITLE
August 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#44]
This MCW is scheduled for content update.  
Opsgility - please review current content and any existing open issues and provide your recommended updates for SME review.

**Comment by paulopsgility** [comment]
- Update SQLDW to Gen2 (Gen1 is deprecated)

- Add Data Factory pipeline to integrate with "customer 360" project defined in the scenario. Students would create an ML model to classify data (potential buyer). An Azure Data Factory pipeline would be created to import future datasets, clean, prepare and score them and write them to the warehouse or Data Lake.

- General updates and fixes

**Comment by DawnmarieDesJardins** [comment]
SME team - 
Please leave feedback and additional suggestions for this update below.
We appreciate your time and expertise!

**Comment by thesqlpro** [comment]
Went through Exercise 1-4. Will try complete exercise 5 and 6.
Went through the documentation for exercise 5 and 6, looks good. Step 6 under task 2 of Exercise 5 has the full user account, maybe better to blur out parts of it for security reasons. (Ex asaadmin@xxx.onmicrosoft.com). The text of the step shows the proper format, however the screenshot shows the full subscription name.

**Comment by DawnmarieDesJardins** [comment]
Closing with August 2019 update merge
