### ISSUE TITLE
No database roles largerc or xlargerc

### ISSUE THREAD

**Issue by sharmibhat9** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#45]
Hi, 

I'm trying to execute the script below to change the user's resource class but getting an error. 
EXEC sp_addrolemember 'xlargerc', 'dataloader';

Error: Cannot alter the role 'xlargerc', because it does not exist or you do not have permission.
Then I checked the sys.database_principals view and the workload management database roles don't exist. 

Please advise.

**Comment by DawnmarieDesJardins** [comment]
@mwasham @paulopsgility 
Hi Michael & Paul.  Please review and advise.

**Comment by paulopsgility** [comment]
I suspect that this is due to the migration from gen1 to gen2 (you can't deploy Gen1 any longer in most regions without contacting support). 

We will verify the issue and provide a fix if necessary in the August update.
