### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by SqlWaldorf** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#47]
The link in the page referring to the Power BI Service is broken (https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-indepth/)

**Comment by DawnmarieDesJardins** [comment]
@SqlWaldorf @paulopsgility 
Thanks Nico!  This workshop is currently going through a quarterly check, we'll make sure that link is fixed.

**Comment by paulopsgility** [comment]
@SqlWaldorf @DawnmarieDesJardins This is resolved.

**Comment by SqlWaldorf** [comment]
Hi, I’m running the workshop later this week, will the updated version be pushed this week or later (just to be aware if I need to warn my students)?
Regards,
Nico

**Comment by DawnmarieDesJardins** [comment]
@SqlWaldorf 
Hi Nico.  This will be QCd and merged today or tomorrow.  I'm reopening this issue and will close it when the merge is complete so you'll be automatically notified.  Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
@SqlWaldorf 
Hi Nico.  I've just merged Paul's August update to the repo master.  He's corrected the link so closing this issue.
