### ISSUE TITLE
Better script for Azure Data Warehouse than hacking the script

### ISSUE THREAD

**Issue by SqlWaldorf** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#48]
In the lab an on-prem database gets scripted for a SQL Server on-prem destination. Afterwards users need to remove the filegroup statements, the use statements, some go statements... But in Management Studio an on-prem database can be scripted for an Azure Data Warehouse destination, which does all this cleanup automatically, so I would suggest to alter Exercise 2, task 2, step 6 in using the Advanced option of scripting, and configure the options Script for the database engine type Microsoft Azure SQL Database, Script for the database engine edition: Microsoft Azure SQL Data Warehouse Edition:
![image](https://user-images.githubusercontent.com/6662571/65024106-7b335800-d934-11e9-841d-40d1e6359a8f.png)
Then the next step where the script needs to altered can be removed!

**Comment by paulopsgility** [comment]
Thanks for the feedback, we'll add this on the next update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue - workshop is being archived.
