### ISSUE TITLE
Inconsistency in Power BI download

### ISSUE THREAD

**Issue by SqlWaldorf** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#49]
Small inconsistency: Near the end of the lab students have to download Power BI. In the first screenshot one has to download the 32 bit version, in the remainder of the screenshots you're using the 64 bit version

**Comment by paulopsgility** [comment]
Thank you for the feedback. We'll update the screenshot on the next test/fix.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  Addressed in October 2019 test/fix.
