### ISSUE TITLE
HOL Ex 1 Task 4

### ISSUE THREAD

**Issue by bryan-c-smith** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#5]
Task 4 asks user to use a region that was previously used.  However, we've provisioned 3-4 resources at this point in the lab and each could have been to a different region.  We need to give clearer guidance here.

**Comment by paulopsgility** [comment]
Added some additional clarity around region selection for this and other resources so they are all going to the same region as the logical SQL Server that is created first.
