### ISSUE TITLE
Exercise 5, step 7: twice the same file is mentioned

### ISSUE THREAD

**Issue by SqlWaldorf** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#50]
The instruction reads: Select the C:\LabFiles\CustomerInfoData.csv, C:\LabFiles\CustomerMrktResearchData.csv and C:\LabFiles\CustomerInfoData.csv files and click the Upload button.

The C:\LabFiles\CustomerInfoData.csv is mentioned twice, probably another filename is needed

**Comment by paulopsgility** [comment]
Thank you for submitting feedback. This is resolved. Since it was technically broken I just went ahead and fixed this one out of band.
