### ISSUE TITLE
Links to migration docs end up at wrong article

### ISSUE THREAD

**Issue by vstrien** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#52]
In the Whiteboard Design Session, participants are expected to review migration overview and high-level checklists. However, this documentation seems to have been removed from Azure, and all links about migration (in general, about schema, about data, and about code) redirect to the overview of developing Azure SQL DW (without any migration tips) : https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-overview-develop

In order to complete the WDS, participants should either be pointed to other docs (containing the same information), or the suggested answers in the training guide (at the text "Answer: The data preparation phase or the pre-migration phase is when you plan your migration. Here is a minimal list of or research to get you started:") have to be updated.

There is some documentation in the Azure Database Migration Guide (https://datamigration.microsoft.com/scenario/sql-to-sqldw?step=1), although this guide also contains links to the (now disappeared) SQLDW Migration docs.

**Comment by paulopsgility** [comment]
@vstrien Thanks for the feedback, I will update the link.

**Comment by paulopsgility** [comment]
The link in the WDS student and trainer guides is updated now. I can't fix the broken links in the documentation.
