### ISSUE TITLE
Passwords sometimes contain backslashes

### ISSUE THREAD

**Issue by vstrien** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#53]
Passwords in the Hands-On Labs sometimes contain a backslash:

> Password: **Demo\@pass123**

However, later on when referring to the same password, it is displayed without a backslash:

> 4. Open a remote desktop session to the SQLCohoDW virtual machine that you created before the lab using the demouser login and **Demo@pass123** password.

**Comment by paulopsgility** [comment]
@vstrien Thanks for the feedback. This is a typo. We'll get that fixed.

**Comment by paulopsgility** [comment]
Resolved
