### ISSUE TITLE
VM is too low on memory

### ISSUE THREAD

**Issue by vstrien** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#54]
The VM has too little memory to function properly. 

* In around 33% of the cases, the post-deployment script fails (at least in region westeurope)
* During the workshopk Google chrome crashes regularly while working in the Azure portal inside the VM

Suggestion: assign a VM with more memory during the deployment in the ARM script.

**Comment by paulopsgility** [comment]
@vstrien I haven't heard of anyone else running into this on this size VM. The VMs used in the ARM template is a D2s_v3 (8GB RAM). We can probably bump it up to an E2s_v3 (16GB RAM) without much impact. I am not able duplicate the issue but I will go with the higher memory VM on the next test/fix or update.

**Comment by vstrien** [comment]
Maybe there are two things at work here:

1. The deployment script didn’t succeed in around 1/3th of the VMs (but this was last week, during which several of my students also had some issues with requesting a new ASDW - so it could have been something with Azure).
2. Google Chrome crashes, and VM users get reports of low memory. Google Chrome is known as a memory hog, which we use in parallel with SSMS AND we’re running SQL Server on this Windows Server machine as well. So maybe that leads to some memory scarcity.

I think the higher memory VM will be great though. Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing issue - workshop is being archived.
