### ISSUE TITLE
HOL Ex 1

### ISSUE THREAD

**Issue by bryan-c-smith** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#6]
We are creating resources in 3-4 resource groups.  We should use one to make clean up easier.

**Comment by paulopsgility** [comment]
One RG is going to be pretty cluttered. To help with cleanup, I changed all the resource group names to start with "Coho". I also eliminated one that was just used for the migration storage account. That storage account now lives in the same RG as the SQL Data Warehouse.
