### ISSUE TITLE
CRITICAL: HOL Ex 1 Task 6

### ISSUE THREAD

**Issue by bryan-c-smith** [Microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#7]
This line:

   From the SQLCohoDW virtual machine, open Internet Explorer, and connect to the Azure Portal

When did we ever create a virtual machine named SQLCohoDW.  I'm lost.

**Comment by paulopsgility** [comment]
Adding a note here about this being created in the "Before the lab" section.
